/**
 * 全局类型定义
 */

// Proficiency levels for knowledge points
export type ProficiencyLevel = 'none' | 'rusty' | 'normal' | 'master';

// Knowledge source type
export type KnowledgeSource = 'ai' | 'manual' | 'import';

export interface ProficiencyConfig {
  label: string;
  color: string;
  bgColor: string;
  reviewIntervalDays: number;
}

export const PROFICIENCY_MAP: Record<ProficiencyLevel, ProficiencyConfig> = {
  none:   { label: '不会', color: '#ef4444', bgColor: '#fef2f2', reviewIntervalDays: 1 },
  rusty:  { label: '生疏', color: '#f59e0b', bgColor: '#fffbeb', reviewIntervalDays: 2.5 },
  normal: { label: '一般', color: '#3b82f6', bgColor: '#eff6ff', reviewIntervalDays: 7 },
  master: { label: '熟练', color: '#10b981', bgColor: '#ecfdf5', reviewIntervalDays: 22 },
};

// User
export interface User {
  id: string;
  nickname: string;
  avatar: string;
  learningDays: number;
  totalPoints: number;
  createdAt: string;
  dailyGoal: number;  // 每日学习目标（题目数）
  dailyNewGoal: number;  // 每日新学目标（知识点数）
  todayQuestions: number;  // 今日已完成题目数
  goalAchievedToday: boolean;  // 今日目标是否达成
  // 【新增】形象相关
  avatarFrame: string | null;  // 当前使用头像框的 icon
  aiSkin: string | null;  // 当前使用 AI 形象的 icon
  background: string | null;  // 当前使用背景的 id
  unlockedAvatars: string[];  // 已解锁的头像列表（emoji）
  unlockedFrames: string[];  // 已解锁的头像框列表（icon）
  unlockedAiSkins: string[];  // 已解锁的 AI 形象列表（icon）
  unlockedBackgrounds: string[];  // 已解锁的背景列表（id）
  customAvatarUrl?: string;  // 自定义头像 URL
  currentBackground?: string;  // 当前背景样式（gradient）
  activeTitle?: string;  // 当前使用的称号ID
}

// Subject / Category
export interface Subject {
  id: string;
  name: string;
  icon: string;
  color: string;
  knowledgePointCount: number;
}

// Chapter within a subject
export interface Chapter {
  id: string;
  subjectId: string;
  name: string;
  order: number;
}

// Knowledge Point
export interface KnowledgePoint {
  id: string;
  subjectId: string;
  chapterId: string;
  name: string;
  explanation: string;
  proficiency: ProficiencyLevel;
  lastReviewedAt: string | null;
  nextReviewAt: string | null;
  reviewCount: number;
  createdAt: string;
  source: KnowledgeSource; // 'ai' | 'manual' | 'import'
}

// Question types
export type QuestionType = 'single_choice' | 'multi_choice' | 'true_false';

export interface QuestionOption {
  id: string;
  text: string;
}

export interface Question {
  id: string;
  knowledgePointId: string;
  subjectId: string;
  type: QuestionType;
  stem: string;
  options: QuestionOption[];
  correctAnswers: string[]; // option ids
  explanation: string;
}

// Quiz / Test
export interface QuizAnswer {
  questionId: string;
  selectedAnswers: string[];
  isCorrect: boolean;
}

export interface QuizResult {
  id: string;
  subjectId: string;
  totalQuestions: number;
  correctCount: number;
  score: number;
  answers: QuizAnswer[];
  completedAt: string;
}

// Wrong answer record
export interface WrongRecord {
  id: string;
  questionId: string;
  wrongAnswers: string[];
  correctAnswers: string[];
  addedAt: string;
  reviewedCount: number;
  lastReviewedAt: string | null;
}

// Question explanation (generated by AI)
export interface QuestionExplanation {
  questionId: string;
  explanation: string;
  createdAt: string;
  updatedAt: string;
  isUserModified: boolean;
}

// Review plan item
export interface ReviewItem {
  knowledgePointId: string;
  type: 'review' | 'new';
  scheduledAt: string;
  completed: boolean;
}

// Learning stats
export interface LearningStats {
  totalKnowledgePoints: number;
  masteredCount: number;
  normalCount: number;
  rustyCount: number;
  noneCount: number;
  totalQuizzes: number;
  averageScore: number;
  streakDays: number;
  weakSubjects: string[];
}

// ===== AI Chat =====

export type AIProvider = 'ollama' | 'volcengine' | 'minimax' | 'douban' | 'openclaw';

// AI预设配置
export interface AIPreset {
  id: string;
  name: string;
  provider: AIProvider;
  modelId?: string;
  groupId?: string;
  description: string;
}

export const AI_PRESETS: AIPreset[] = [
  { id: 'ollama-local', name: 'Ollama (本地)', provider: 'ollama', description: '本地部署，无需API密钥' },
  { id: 'douban', name: '豆包 API', provider: 'douban', description: '火山引擎豆包大模型，需密钥' },
  { id: 'volcengine', name: '火山引擎', provider: 'volcengine', modelId: 'ep-xxxxx', description: '豆包大模型' },
  { id: 'minimax', name: 'MiniMax', provider: 'minimax', groupId: 'group-xxxxx', description: '海螺问问' },
  { id: 'custom', name: '自定义', provider: 'ollama', description: '手动输入API配置' },
];

export interface AIConfig {
  provider: AIProvider;
  presetId?: string;
  model?: string;
  apiKey?: string;
  modelId?: string;
  groupId?: string;
}

export interface ProviderInfo {
  name: AIProvider;
  available: boolean;
  models: string[];
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'ai';
  content: string;
  timestamp: string;
  relatedQuestionId?: string;
  isStreaming?: boolean;
}

export interface AIChatSession {
  messages: ChatMessage[];
  isLoading: boolean;
  generatedQuestions: string[];
}

// Page routing
export type PageName =
  | 'home'
  | 'knowledge'
  | 'quiz'
  | 'knowledge-map'
  | 'profile'
  | 'settings'
  | 'login'
  | 'daily-question'
  | 'subject-detail'
  | 'knowledge-detail'
  | 'quiz-session'
  | 'quiz-result'
  | 'wrong-book'
  | 'review-session'
  | 'add-knowledge'
  | 'import-knowledge'
  | 'checkin'
  | 'achievements'
  | 'shop'
  | 'ranking'
  | 'lottery'
  | 'ai-chat'
  | 'inventory'
  | 'mail'
  | 'avatar-edit'
  | 'flashcard-learning';

// ===== 激励体系 =====

// Check-in / Sign-in
export interface CheckinRecord {
  date: string; // YYYY-MM-DD
  type: 'normal' | 'makeup' | 'team';
  teamId?: string;
  lotteryResult?: LotteryResult;
}

export interface CheckinState {
  records: CheckinRecord[];
  streak: number;
  makeupCards: number;
  totalCheckins: number;
  lotteryPity: LotteryPityState;
}

// ===== Lottery / 抽签系统 =====

export type LotteryTier = 'SSR' | 'SR' | 'R' | 'N' | 'NN';

export interface LotteryTierConfig {
  tier: LotteryTier;
  label: string;
  probability: number;
  rewardType: 'makeup_card' | 'coins' | 'blessing';
  rewardAmount: number;
  color: string;
  icon: string;
}

export interface LotteryResult {
  tier: LotteryTier;
  reward: { type: 'makeup_card' | 'coins' | 'blessing'; amount: number };
  blessing?: string;
  isPity: boolean;
  timestamp: string;
}

export interface LotteryPityState {
  sinceLastSR: number;
  sinceLastSSR: number;
}

export interface LotteryPopup {
  show: boolean;
  result: LotteryResult | UpPoolResult | null;
  pool: 'regular' | 'up';
  phase: 'shaking' | 'revealing' | 'result';
  isTenDraw?: boolean;
  allResults?: (LotteryResult | UpPoolResult)[];
}

// ===== Draw Balance / 抽签次数 =====

export interface DrawBalance {
  regular: number;
  up: number;
}

// ===== UP Pool / UP池限时奖池 =====

export interface UpPoolItem {
  id: string;
  name: string;
  description: string;
  icon: string;
  type: 'avatar_frame' | 'background' | 'theme' | 'title';
  rarity: 'N' | 'R' | 'SR' | 'SSR';
  probability: number;
  owned: boolean;
}

export interface UpPoolConfig {
  id: string;
  name: string;
  description: string;
  banner: string;
  items: UpPoolItem[];
  startDate: string;
  endDate: string;
  active: boolean;
}

export interface UpPoolResult {
  item: UpPoolItem;
  isNew: boolean;
  timestamp: string;
}

// ===== Team / 组队学习 =====

export interface TeamMember {
  id: string;
  name: string;
  avatar: string;
  avatarFrame?: string;
  isSimulated: boolean;
  progress: TeamMemberProgress;
}

export interface TeamMemberProgress {
  taskCompletionRate: number;
  studyMinutes: number;
  isReady: boolean;
  lastUpdated: string;
}

export interface TeamState {
  id: string;
  inviteCode: string;
  members: TeamMember[];
  status: 'waiting' | 'active' | 'dissolved';
  createdAt: string;
  todayCheckedIn: boolean;
}

// Achievements
export type AchievementCategory = 'beginner' | 'learning' | 'quiz' | 'hidden';

export interface Achievement {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: AchievementCategory;
  condition: AchievementCondition;
  reward: { coins: number };
  unlocked: boolean;
  unlockedAt: string | null;
}

export interface AchievementCondition {
  type: 'first_learn' | 'first_checkin' | 'streak_days' | 'master_count' | 'perfect_quiz' | 'clear_wrong'
       | 'total_knowledge' | 'total_checkins' | 'total_quizzes' | 'makeup_used' | 'one_session_correct';
  value: number;
}

// Shop
export type ShopItemType = 'makeup_card' | 'avatar_frame' | 'theme_skin' | 'ai_skin' | 'background' | 'theme' | 'vip_card' | 'coin_bag';

export interface ShopItem {
  id: string;
  name: string;
  description: string;
  icon: string;
  type: ShopItemType;
  price: number;
  rarity?: 'N' | 'R' | 'SR' | 'SSR';
  owned: boolean;
}

// Ranking
export interface RankEntry {
  rank: number;
  nickname: string;
  avatar: string;
  avatarFrame?: string;
  value: number;
  isMe: boolean;
}

// Achievement unlock popup
export interface AchievementPopup {
  achievement: Achievement;
  show: boolean;
}

// ===== Inventory / 背包系统 =====
export type InventoryItemType = 'makeup_card' | 'avatar_frame' | 'background' | 'theme' | 'title' | 'coin_bag' | 'vip_card';

export interface InventoryItem {
  id: string;
  type: InventoryItemType;
  name: string;
  description: string;
  icon: string;
  rarity: 'N' | 'R' | 'SR' | 'SSR';
  quantity: number;
  obtainedAt: string;
  source: 'lottery' | 'mail' | 'achievement' | 'shop' | 'manual';
  usable: boolean;  // 是否可以使用
  expiresAt?: string;  // 过期时间
}

export interface InventoryState {
  items: InventoryItem[];
}

// ===== Mail / 邮件系统 =====
export type MailAttachmentType = 'makeup_card' | 'avatar_frame' | 'background' | 'title' | 'coin' | 'vip';

export interface MailAttachment {
  type: MailAttachmentType;
  name: string;
  description?: string;
  icon?: string;
  rarity?: 'N' | 'R' | 'SR' | 'SSR';
  quantity: number;
  claimed: boolean;
}

export interface MailItem {
  id: string;
  title: string;
  content: string;
  sender: string;
  sentAt: string;
  read: boolean;
  attachments: MailAttachment[];
  claimDeadline: string;  // 领取截止日期
  systemMail: boolean;  // 是否是系统邮件
  claimed: boolean;  // 是否已领取所有附件
  version: number;  // 版本号，用于判断更新
}

export interface MailState {
  mails: MailItem[];
  currentVersion: number;
}

// ===== AI 相关类型 =====
export interface GenerateSmartQuizResult {
  question: Question | null;
  selectedKnowledgePoint?: string;
  mode: 'random' | 'smart';
}

export interface StudyReportParams {
  knowledgeStats: Array<{
    name: string;
    masteryLevel: number;
    wrongCount: number;
  }>;
  totalKnowledgePoints: number;
  masteredCount: number;
  subjectName: string;
  provider?: string;
}

// ===== 主题相关类型 =====
export interface ThemeConfig {
  primary: string;
  primaryLight: string;
  primaryDark: string;
  secondary: string;
  secondaryLight: string;
  accent: string;
  accentLight: string;
  danger: string;
  warning: string;
  success: string;
  bg: string;
  bgCard: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  border: string;
  profNone: string;
  profRusty: string;
  profNormal: string;
  profMaster: string;
  // 新增：AI问答框样式
  aiChatBg: string;
  aiChatBorder: string;
  aiChatIconColor: string;
  // 新增：图标颜色
  iconColors: {
    checkin: string;
    achievement: string;
    shop: string;
    ranking: string;
    quiz: string;
    knowledge: string;
    knowledgeMap: string;
    wrongBook: string;
    aiChat: string;
  };
  // 新增：圆角风格
  borderRadius: 'small' | 'medium' | 'large' | 'cute';
  // 新增：阴影强度
  shadowIntensity: 'none' | 'light' | 'medium' | 'heavy';
}

export const themes: Record<string, ThemeConfig> = {
  default: {
    primary: '#6366f1',
    primaryLight: '#818cf8',
    primaryDark: '#4f46e5',
    secondary: '#f59e0b',
    secondaryLight: '#fbbf24',
    accent: '#10b981',
    accentLight: '#34d399',
    danger: '#ef4444',
    warning: '#f59e0b',
    success: '#10b981',
    bg: '#f8fafc',
    bgCard: '#ffffff',
    textPrimary: '#1e293b',
    textSecondary: '#64748b',
    textMuted: '#94a3b8',
    border: '#e2e8f0',
    profNone: '#ef4444',
    profRusty: '#f59e0b',
    profNormal: '#3b82f6',
    profMaster: '#10b981',
    aiChatBg: 'linear-gradient(135deg, rgba(238, 242, 255, 0.8), rgba(221, 214, 254, 0.8))',
    aiChatBorder: 'rgba(139, 92, 246, 0.3)',
    aiChatIconColor: '#8b5cf6',
    iconColors: {
      checkin: '#f97316',
      achievement: '#eab308',
      shop: '#a855f7',
      ranking: '#3b82f6',
      quiz: '#6366f1',
      knowledge: '#10b981',
      knowledgeMap: '#8b5cf6',
      wrongBook: '#ef4444',
      aiChat: '#8b5cf6',
    },
    borderRadius: 'medium',
    shadowIntensity: 'light',
  },
  dark: {
    primary: '#818cf8',
    primaryLight: '#a5b4fc',
    primaryDark: '#4f46e5',
    secondary: '#fbbf24',
    secondaryLight: '#fcd34d',
    accent: '#34d399',
    accentLight: '#6ee7b7',
    danger: '#f87171',
    warning: '#fbbf24',
    success: '#34d399',
    bg: '#1e1b4b',
    bgCard: 'rgba(255, 255, 255, 0.1)',
    textPrimary: '#f8fafc',
    textSecondary: '#cbd5e1',
    textMuted: '#94a3b8',
    border: 'rgba(255, 255, 255, 0.25)',
    profNone: '#f87171',
    profRusty: '#fbbf24',
    profNormal: '#60a5fa',
    profMaster: '#34d399',
    aiChatBg: 'linear-gradient(135deg, rgba(139, 92, 246, 0.2), rgba(168, 85, 247, 0.2))',
    aiChatBorder: 'rgba(139, 92, 246, 0.4)',
    aiChatIconColor: '#c4b5fd',
    iconColors: {
      checkin: '#fbbf24',
      achievement: '#fcd34d',
      shop: '#c4b5fd',
      ranking: '#93c5fd',
      quiz: '#818cf8',
      knowledge: '#34d399',
      knowledgeMap: '#c4b5fd',
      wrongBook: '#f87171',
      aiChat: '#c4b5fd',
    },
    borderRadius: 'medium',
    shadowIntensity: 'light',
  },
  forest: {
    primary: '#10b981',
    primaryLight: '#34d399',
    primaryDark: '#059669',
    secondary: '#f59e0b',
    secondaryLight: '#fbbf24',
    accent: '#6366f1',
    accentLight: '#818cf8',
    danger: '#ef4444',
    warning: '#f59e0b',
    success: '#10b981',
    bg: '#064e3b',
    bgCard: 'rgba(255, 255, 255, 0.1)',
    textPrimary: '#f8fafc',
    textSecondary: '#dcfce7',
    textMuted: '#94a3b8',
    border: 'rgba(255, 255, 255, 0.25)',
    profNone: '#ef4444',
    profRusty: '#f59e0b',
    profNormal: '#6366f1',
    profMaster: '#10b981',
    aiChatBg: 'linear-gradient(135deg, rgba(16, 185, 129, 0.2), rgba(52, 211, 153, 0.2))',
    aiChatBorder: 'rgba(16, 185, 129, 0.4)',
    aiChatIconColor: '#34d399',
    iconColors: {
      checkin: '#fbbf24',
      achievement: '#fcd34d',
      shop: '#a78bfa',
      ranking: '#93c5fd',
      quiz: '#10b981',
      knowledge: '#34d399',
      knowledgeMap: '#a78bfa',
      wrongBook: '#f87171',
      aiChat: '#34d399',
    },
    borderRadius: 'medium',
    shadowIntensity: 'light',
  },
  warm: {
    primary: '#f97316',
    primaryLight: '#fb923c',
    primaryDark: '#ea580c',
    secondary: '#6366f1',
    secondaryLight: '#818cf8',
    accent: '#10b981',
    accentLight: '#34d399',
    danger: '#ef4444',
    warning: '#f59e0b',
    success: '#10b981',
    bg: '#fef2f2',
    bgCard: '#ffffff',
    textPrimary: '#1e293b',
    textSecondary: '#64748b',
    textMuted: '#94a3b8',
    border: '#fecaca',
    profNone: '#ef4444',
    profRusty: '#f59e0b',
    profNormal: '#6366f1',
    profMaster: '#10b981',
    aiChatBg: 'linear-gradient(135deg, rgba(249, 115, 22, 0.1), rgba(251, 146, 60, 0.1))',
    aiChatBorder: 'rgba(249, 115, 22, 0.3)',
    aiChatIconColor: '#f97316',
    iconColors: {
      checkin: '#f97316',
      achievement: '#eab308',
      shop: '#a855f7',
      ranking: '#3b82f6',
      quiz: '#f97316',
      knowledge: '#10b981',
      knowledgeMap: '#8b5cf6',
      wrongBook: '#ef4444',
      aiChat: '#f97316',
    },
    borderRadius: 'medium',
    shadowIntensity: 'light',
  },
  pink: {
    primary: '#ec4899',
    primaryLight: '#f472b6',
    primaryDark: '#db2777',
    secondary: '#f97316',
    secondaryLight: '#fb923c',
    accent: '#8b5cf6',
    accentLight: '#a78bfa',
    danger: '#ef4444',
    warning: '#f59e0b',
    success: '#10b981',
    bg: '#fdf2f8',
    bgCard: 'rgba(255, 255, 255, 0.9)',
    textPrimary: '#831843',
    textSecondary: '#be185d',
    textMuted: '#f472b6',
    border: '#fbcfe8',
    profNone: '#ef4444',
    profRusty: '#f59e0b',
    profNormal: '#8b5cf6',
    profMaster: '#10b981',
    aiChatBg: 'linear-gradient(135deg, rgba(236, 72, 153, 0.15), rgba(251, 113, 133, 0.15))',
    aiChatBorder: 'rgba(236, 72, 153, 0.4)',
    aiChatIconColor: '#ec4899',
    iconColors: {
      checkin: '#f472b6',
      achievement: '#fbbf24',
      shop: '#ec4899',
      ranking: '#f472b6',
      quiz: '#ec4899',
      knowledge: '#10b981',
      knowledgeMap: '#f472b6',
      wrongBook: '#ef4444',
      aiChat: '#ec4899',
    },
    borderRadius: 'cute',
    shadowIntensity: 'light',
  },
  blue: {
    primary: '#3b82f6',
    primaryLight: '#60a5fa',
    primaryDark: '#2563eb',
    secondary: '#f59e0b',
    secondaryLight: '#fbbf24',
    accent: '#10b981',
    accentLight: '#34d399',
    danger: '#ef4444',
    warning: '#f59e0b',
    success: '#10b981',
    bg: '#dbeafe',
    bgCard: '#ffffff',
    textPrimary: '#1e293b',
    textSecondary: '#64748b',
    textMuted: '#94a3b8',
    border: '#bfdbfe',
    profNone: '#ef4444',
    profRusty: '#f59e0b',
    profNormal: '#3b82f6',
    profMaster: '#10b981',
    aiChatBg: 'linear-gradient(135deg, rgba(59, 130, 246, 0.1), rgba(96, 165, 250, 0.1))',
    aiChatBorder: 'rgba(59, 130, 246, 0.3)',
    aiChatIconColor: '#3b82f6',
    iconColors: {
      checkin: '#f97316',
      achievement: '#eab308',
      shop: '#a855f7',
      ranking: '#3b82f6',
      quiz: '#3b82f6',
      knowledge: '#10b981',
      knowledgeMap: '#8b5cf6',
      wrongBook: '#ef4444',
      aiChat: '#3b82f6',
    },
    borderRadius: 'medium',
    shadowIntensity: 'light',
  },
  aurora: {
    primary: '#8b5cf6',
    primaryLight: '#a78bfa',
    primaryDark: '#7c3aed',
    secondary: '#ec4899',
    secondaryLight: '#f472b6',
    accent: '#14b8a6',
    accentLight: '#2dd4bf',
    danger: '#ef4444',
    warning: '#f59e0b',
    success: '#10b981',
    bg: '#1e3a5f',
    bgCard: 'rgba(255, 255, 255, 0.1)',
    textPrimary: '#f8fafc',
    textSecondary: '#cbd5e1',
    textMuted: '#94a3b8',
    border: 'rgba(255, 255, 255, 0.25)',
    profNone: '#f87171',
    profRusty: '#fbbf24',
    profNormal: '#60a5fa',
    profMaster: '#34d399',
    aiChatBg: 'linear-gradient(135deg, rgba(139, 92, 246, 0.2), rgba(236, 72, 153, 0.2))',
    aiChatBorder: 'rgba(139, 92, 246, 0.4)',
    aiChatIconColor: '#c4b5fd',
    iconColors: {
      checkin: '#fbbf24',
      achievement: '#fcd34d',
      shop: '#c4b5fd',
      ranking: '#93c5fd',
      quiz: '#8b5cf6',
      knowledge: '#2dd4bf',
      knowledgeMap: '#c4b5fd',
      wrongBook: '#f87171',
      aiChat: '#c4b5fd',
    },
    borderRadius: 'medium',
    shadowIntensity: 'light',
  },
};

export const getThemeByBackgroundId = (backgroundId?: string): ThemeConfig => {
  if (!backgroundId) return themes.default;
  
  if (backgroundId.includes('bg-r-1') || backgroundId.includes('bg-ssr-1')) {
    return themes.dark;
  }
  
  if (backgroundId.includes('bg-r-2') || backgroundId.includes('bg-sr-2')) {
    return themes.forest;
  }
  
  if (backgroundId.includes('bg-r-3') || backgroundId.includes('bg-r-4') || backgroundId.includes('bg-sr-4')) {
    return themes.warm;
  }
  
  if (backgroundId.includes('bg-sr-1')) {
    return themes.pink;
  }
  
  if (backgroundId.includes('bg-n-2') || backgroundId.includes('bg-sr-3')) {
    return themes.blue;
  }
  
  if (backgroundId.includes('bg-ssr-2') || backgroundId.includes('bg-ssr-3')) {
    return themes.aurora;
  }
  
  return themes.default;
};

// ===== Flashcard Learning Types =====

// Study record for flashcard learning
export interface StudyRecord {
  date: string;           // ISO date string
  type: 'flashcard';      // Always 'flashcard' for flashcard records
  score: number;          // 100/80/60/40...
  knowledgePointId: string;
}

// Quiz record for question answers
export interface QuizRecord {
  date: string;           // ISO date string
  questionId: string;
  correct: boolean;
  score: number;         // 100/80/60/40...
  knowledgePointId: string;
}

// Extended KnowledgePoint with learning records
export interface KnowledgePointExtended extends KnowledgePoint {
  studyRecords: StudyRecord[];
  quizRecords: QuizRecord[];
  currentScore: number;  // Combined score 0-100
  memoryTip?: string;    // Memory tip/hint
}
