name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install app dependencies
        run: npm ci

      - name: Install server dependencies
        run: npm ci
        working-directory: server

      - name: Test
        run: npm test

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
